name: ci

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Setup Volta
        uses: volta-cli/action@v4.2.1
      - name: Install dependencies
        run: npm ci
      - name: Test project
        run: npm run test
